#:schema node_modules/wrangler/config-schema.json
name = "aimpact"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[vars]
PUBLIC_BACKEND_URL = "https://eblo7vdluldh7a74tp8o30v31g.ingress.d3akash.cloud"
VITE_DEPOSIT_ADDRESS = "GorN1wMsaWp75QJYtU8NrCu9GCgTtPiUeDRX3ccLZ5jj"
VITE_REWARDS_SHARING_PERCENT = "10"
VITE_PRICE_PER_MESSAGE_IN_SOL = "0.003"
ENVIRONMENT = "production"

[env.preview]
name = "aimpact-preview"
[env.preview.vars]
PUBLIC_BACKEND_URL = "https://p5c2vgrgn9emb2lbdukc6el728.ingress.d3akash.cloud"
